spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
cognito:
  user-pool-id: ${COGNITO_USER_POOL_ID}
  client-id: ${COGNITO_CLIENT_ID}
  region: ${COGNITO_REGION}